#Name of the workflow
name: QnA-Infra-Deploy

#Triggers to run the workflow
on:
  push: #To trigger workflow when an update in pushed onto main branch
    branches: [main]
  pull_request: #To trigger workflow when a PR is raised against main branch
    branches: [main]
  workflow_dispatch: #To trigger workflow manually using GUI

jobs:
  # Deploy Job
  deploy:
    name: Deploy Infrastructure to Azure
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository #Checkout the Repository into the agent
        uses: actions/checkout@v2

      - name: Set Environment Variables - Build #Set Variable
        uses: deep-mm/set-variables@v1.0
        with:
          variableFileName: "qna"

      - name: Login to Azure # Login to Azure with credentials of service principal stored in secrets
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Resource Group # Create Resource Group using azure cli commands
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az group create --name "${{ env.resourceGroup }}" --location "${{ env.location }}"
        
      - name: Provision QnA Maker & Bot Service # Provision QnA Maker & Bot service resources
        uses: Azure/arm-deploy@main
        id: armOutput
        with:
          scope: 'resourcegroup'
          subscriptionId: '${{ env.subscriptionId }}'
          resourceGroupName: '${{ env.resourceGroup }}'
          template: 'ARM_Template/deploy.json'
          deploymentMode: Incremental
          parameters: 'name="${{ env.qnaName }}" Location="${{ env.location }}"'

      - name: Create SubscriptionKey Secret
        uses: gliech/create-github-secret-action@v1
        with:
          name: QnA_SubscriptionKey
          value: ${{ steps.armOutput.outputs.subscriptionKey }}
          pa_token: ${{ secrets.PAT }}

  deploy-language:
    name: Deploy Language Project
    # The type of runner that the job will run on
    runs-on: windows-latest
    needs: [deploy]
    steps:
      - name: Checkout Repository #Checkout the Repository into the agent
        uses: actions/checkout@v2

      - name: Set Environment Variables - Build #Set Variable
        uses: deep-mm/set-variables@v1.0
        with:
          variableFileName: "qna"

      - name: Deploy QnA Language Project
        run: .github/scripts/createLanguageProject.ps1 -QnAName "${{ env.qnaName }}" -projectName "${{ env.qnaName }}" -subscriptionKey "${{ secrets.subscriptionKey }}"
        shell: powershell