name: GitHub Issues QnA Bot

on:
  issue_comment:
    types:
      - created

jobs:
  # Deploy Job
  get-answer:
    name: Get Answer from QnA Service
    if: ${{ startsWith(github.event.comment.body, '@bot') }}
    # The type of runner that the job will run on
    runs-on: windows-latest

    steps:
      - name: Call QnA Service
        id: qna
        run: |
          $question = ${{ github.event.comment.body }}.Replace('@bot', '');
          $body = @{"top"                  = 1
              "question"                   = "$question"
              "includeUnstructuredSources" = $true
              "confidenceScoreThreshold"   = 0
          }
          $response = Invoke-RestMethod -Uri "https://${{ secrets.qnaName }}-language.cognitiveservices.azure.com/language/:query-knowledgebases/?projectName=${{ secrets.qnaName }}&api-version=2021-10-01&deploymentName=production" -Method POST -Headers @{"Ocp-Apim-Subscription-Key" = "${{ secrets.QnA_SubscriptionKey }}"; "Content-Type" = "application/json" } -ContentType "application/json" -Body $($body | ConvertTo-Json)
          echo "::set-output name=answer::$($response.answers[0].answer)"
#.github/scripts/getAnswer.ps1 -QnAName "${{ secrets.qnaName }}" -projectName "${{ secrets.qnaName }}" -question "${{ github.event.comment.body }}" -subscriptionKey "${{ secrets.QnA_SubscriptionKey }}"
        shell: powershell

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ${{ github.event.comment.user.login }}, "${{ steps.qna.outputs.answer }}"
